name: Integration-Calling-Workflow
run-name: ${{ github.actor }} ran pipeline for APIGEE Integration deployment.
on:
  pull_request:
      branches:
        - development
        - staging
        - production
      types:
        - opened
jobs:
  Integration_Deployment_workflow:
    uses: project/apigee-cicd/.github/workflows/Integration-CICD.yml@main
    secrets: inherit
